### ISSUE TITLE
Report of next purchase isn't always displayed, and it would be nice if it could report when it changes.

### ISSUE THREAD

**Issue by lmgjerstad** [lmgjerstad/cookieclicker#5]

**Comment by AdrianGjerstad** [comment]
This is semi-fixed with the implementation of UI, however this is not done through the console.

**Comment by AdrianGjerstad** [comment]
This may just be a problem with the UI, but it now seems to report things to buy way outside of the possible range of things to buy in the first place. At other times it reports correctly, but not always.
